// Terrain: the ground the whole town sits on.
//
// Ground is drawn as isometric diamond tiles, one per world tile, and the tiles
// must tile edge to edge — a visible seam between two tiles of the same kind
// would draw a grid over the field and turn a place back into a diagram.
//
// The one rule that makes that work: a tile fills every pixel of its own 16x8
// diamond, and the diamond is generated by projecting a 16x16 world square, so a
// neighbouring tile's projection abuts it exactly rather than approximately.
//
// Variation is what keeps a large field from reading as flat colour, and it must
// be deterministic: the same world position always gets the same variant, or the
// same repo would draw a different town on every reload (ADR-0012). That is why
// variant selection is a hash of world coordinates and the variants themselves
// are authored, never random.

import { P, type Ramp } from "./palette";
import { IsoPix } from "./iso";
import { type Pix } from "./surface";

/** The world-space edge length of one ground tile. A world unit is one art
 *  pixel, so a 16-unit square projects to a diamond 16 wide and 8 tall. */
export const TILE = 16;

/**
 * The size of a rendered tile, and where its world origin sits inside it.
 *
 * A 16-unit world square projects across 17 pixels, not 16: the four corners
 * land on x = 8, 16, 0 and 8 again, so the span is inclusive of both ends.
 * Getting this wrong is silent and severe — an origin one row too low clips the
 * bottom half of every tile and leaves the void showing through the field — so
 * the numbers are exported here and the bake reads them rather than restating
 * them.
 */
export const TILE_PX = { w: TILE + 1, h: TILE / 2 + 1, ox: TILE / 2, oy: 0 } as const;

/**
 * The kinds of ground the town draws.
 *
 * Every kind here is one the scene actually places: grass for the field and the
 * town, `grassDark` for the land outside it, `earth` for a test district and
 * the Workshop/Depot plots, `yard` for the Yard. There is deliberately no
 * `road`: the layout puts districts in wrapped rows and the roads are the gaps
 * between them (ADR-0012), so a road tile had nothing to place it and was baked
 * as dead art.
 */
export type Ground = "grass" | "grassDark" | "yard" | "earth" | "deck" | "flags";

/** Every kind, in a stable order, so the bake does not depend on key order. */
export const GROUND_KINDS: readonly Ground[] = ["grass", "grassDark", "yard", "earth", "deck", "flags"];

/** Each kind's ramp, base index, and its lit and shadowed facet steps. */
const GROUND_RAMP: Record<Ground, { ramp: Ramp; base: number; lit: string; dark: string }> = {
  grass: { ramp: P.grass, base: 2, lit: P.grass[3], dark: P.grass[1] },
  grassDark: { ramp: P.grass, base: 1, lit: P.grass[2], dark: P.grass[0] },
  // The three places get three different surfaces, and that is the point rather
  // than polish. Two of them sharing `earth` was the first version, and the
  // Workshop and Depot came out as one continuous brown field with a divider
  // drawn across it — a reader could not tell where one ended and the next
  // began, which is exactly the question the three places exist to answer.
  //
  //   - the Yard is packed dirt: a whole site's traffic, so it is scuffed and
  //     unstaked. It takes its own two steps rather than a step of the earth
  //     ramp, because packed dirt is a different surface, not a darker one.
  yard: { ramp: P.earth, base: 1, lit: P.yardFloorLit, dark: P.yardFloorDark },
  // Bare earth: the general ground of a test district, and nothing else. It is
  // left plain on purpose so the three places can each look made.
  earth: { ramp: P.earth, base: 2, lit: P.earth[3], dark: P.earth[1] },
  // The Workshop is boarded: timber laid down to work on, because a shop floor
  // takes a dropped chisel better than dirt does. Wood ramp, so it is warm and
  // clearly not the Yard's dirt.
  deck: { ramp: P.wood, base: 1, lit: P.wood[3], dark: P.wood[2] },
  // The Depot is flagged: stone slabs for a room things are stacked and
  // inventoried in. Grey, cool, and the only place in the town on stone at
  // ground level — which is what makes it read as indoors.
  //
  // It takes `stone[2]` as its base rather than `stone[1]`, and that is a real
  // correction rather than a taste call: the rim and the lip both come from the
  // ramp's darkest step, so a surface sitting on that same step has an edge
  // that draws nothing — the tile renders but the boundary is invisible, which
  // is the exact failure the edge test exists to catch. One step of separation
  // between the surface and its own dark step is the minimum that shows.
  flags: { ramp: P.stone, base: 2, lit: P.stone[3], dark: P.stone[1] },
};

/**
 * A deterministic hash of integer world coordinates, returning 0..3.
 *
 * The mix is the point, not decoration. A plain `wx * P ^ wy * Q` looks random
 * and is not: the scene samples this at multiples of TILE, so every low bit of
 * both inputs is zero, and the result would be 0 for every tile in the town —
 * a variation system that silently never varies. Folding the high bits down
 * with xor-shifts and one multiply is what makes neighbouring tiles differ.
 *
 * Deterministic by construction: the same position always yields the same
 * variant, so the same repo always draws the same town (ADR-0012).
 */
export function tileVariant(wx: number, wy: number): number {
  let h = (((wx | 0) * 73856093) ^ ((wy | 0) * 19349663)) | 0;
  h ^= h >>> 15;
  h = Math.imul(h, 0x2c1b3c6d);
  h ^= h >>> 12;
  h = Math.imul(h, 0x297a2d39);
  h ^= h >>> 15;
  return (h >>> 0) % 4;
}
/**
 * Detail scatter: where the blades, pebbles or cracks sit in each variant.
 *
 * Written as a table rather than computed, because authored scatter looks
 * intended and a hash-driven scatter looks like noise. Offsets are in world
 * units within the tile, and each entry is a pair of (across, along) so a
 * detail lands at a chosen spot on the diamond.
 */
const SCATTER: readonly (readonly [number, number])[][] = [
  [[3, 4], [9, 6], [12, 3], [6, 11]],
  [[5, 3], [11, 5], [4, 9], [13, 10], [8, 12]],
  [[7, 2], [2, 7], [12, 8], [6, 13]],
  [[4, 5], [10, 4], [3, 11], [11, 12], [8, 7], [13, 6]],
];

/**
 * groundTile renders one diamond of ground.
 *
 * The tile is built as two facets split along the diamond's long axis: the
 * upper-left half takes the lit step and the lower-right the dark one. That
 * split is the whole lighting model of the ground — the town's sun is up and to
 * the left (see iso.ts), so every flat surface leans the same way, and a field
 * of tiles gains a direction without any of them carrying a gradient.
 *
 * Ordered dither at the seam is what stops the two halves meeting in a hard line
 * that would read as a crease rather than as light.
 */
export function groundTile(kind: Ground, variant: number): Pix {
  const { base, lit, dark } = GROUND_RAMP[kind];
  const v = ((variant % 4) + 4) % 4;
  // The origin is at the diamond's top corner, so the cel's own box starts at
  // (0, 0) and the scene can place a whole field of tiles with one subtraction.
  const iso = new IsoPix(TILE_PX.w, TILE_PX.h, TILE_PX.ox, TILE_PX.oy);

  // Fill the whole footprint first, so no pixel of the diamond is left empty; a
  // gap would let the void show through the field.
  iso.footprint(0, 0, TILE, TILE, 0, GROUND_RAMP[kind].ramp[base]);

  // The two facets. `wy < wx` is the upper-left half in world terms: a larger wy
  // projects further left, so this split runs along the diamond's long axis.
  for (let wy = 0; wy <= TILE; wy++) {
    for (let wx = 0; wx <= TILE; wx++) {
      const upperLeft = wy < wx;
      if (upperLeft) {
        // Ordered 25% dither on the lit facet: one pixel in four, laid on a
        // fixed lattice. Random dither at this size is noise; a lattice reads
        // as a texture.
        if ((wx + wy * 2) % 4 === 0) iso.plot(wx, wy, 0, lit);
      } else {
        // Ordered 50% checker on the dark facet, which is what gives the
        // shadow side of the tile a tooth rather than a flat fill.
        if ((wx + wy) % 2 === 0) iso.plot(wx, wy, 0, dark);
      }
    }
  }

  // A rim on the made surfaces rather than the fields: a Yard, a shop floor and
  // a flagged room are all constructed, so they have an edge where the making
  // stops. Grass and bare earth do not, and giving them one would draw a grid
  // over a field.
  if (kind !== "grass" && kind !== "grassDark" && kind !== "earth") {
    iso.footprintRim(0, 0, TILE, TILE, 0, GROUND_RAMP[kind].ramp[0]);
  }

  // Authored detail, per surface. Each kind gets the marks its own material
  // would carry, because a single scatter drawn in every kind's darkest step is
  // what makes four different surfaces look like one surface at four settings:
  //
  //   - grass has blades,
  //   - dirt has pebbles and scuffs,
  //   - boarding has grain and the dark line of a board joint,
  //   - flagging has the mortar lines between slabs.
  const scatter = SCATTER[v];
  scatter.forEach(([ax, ay], i) => {
    switch (kind) {
      case "grass":
      case "grassDark":
        // A blade is two pixels: a lit tip over a dark root, which is the
        // smallest thing that reads as a plant rather than as a speck.
        iso.plot(ax, ay, 0, i % 2 === 0 ? P.grassLit : lit);
        iso.plot(ax, ay + 1, 0, P.grass[0]);
        break;
      case "deck":
        // Grain: a run of three pixels along the board, in the step below the
        // surface, which is what makes laid timber read as boards and not as a
        // brown floor.
        iso.row(ax, Math.min(TILE, ax + 3), ay, 0, P.wood[0]);
        break;
      case "flags":
        // Slab joints: a short L per tile, in the ramp's darkest step, so two
        // adjacent tiles' joints meet and read as mortar rather than as dashes.
        iso.column(ax, ay, 0, 0, P.stone[0]);
        iso.plot(ax, Math.min(TILE, ay + 2), 0, P.stone[0]);
        break;
      default:
        // Dirt: a pebble over a scuff, which is what a walked surface looks
        // like rather than a swept one.
        iso.plot(ax, ay, 0, i % 2 === 0 ? P.earth[3] : P.earth[0]);
        iso.plot(Math.min(TILE, ax + 1), ay, 0, dark);
        break;
    }
  });

  return iso.pix;
}
/**
 * A tile's four diamond edges, named by where they appear in the picture.
 *
 * `north` and `west` are the two far edges and `east`/`south` the two near
 * ones. The names matter at the call site: a region's border in **x** takes
 * `west`/`east` and a border in **y** takes `north`/`south`. Pairing a border
 * with the band that hugs the other axis draws the rim across the middle of a
 * plate and leaves the real boundary bare.
 */
export type Edge = "north" | "east" | "south" | "west";

/** Every edge, in a stable order, so the bake does not depend on key order. */
export const EDGES: readonly Edge[] = ["north", "east", "south", "west"];

/**
 * groundEdgeTile draws a rim along one boundary of a tile.
 *
 * This is the "edge piece" a tile set needs and a bare kind flip cannot give.
 * Where two regions of different ground meet, the boundary is not a line to be
 * drawn but a strip of ground that belongs to *this* plate: a two-unit band of
 * packed, darkened earth dithered along the edge, closed by a one-pixel lip on
 * the outermost row. A plate therefore ends deliberately instead of simply
 * stopping, which is what stops a district reading as a rectangle cut out of a
 * field.
 *
 * It is deliberately a rim and not a two-material blend: blending would mean
 * knowing the neighbouring kind at bake time, which is five kinds times five
 * neighbours times four edges times four variants of cel for a two-unit band.
 * The rim gets the compositional job done with one cel per edge.
 *
 * Both colours come from the tile's own ramp and both differ from the tile's
 * base fill. An earlier version took its lip colour from the tile's base, which
 * drew nothing at all — the rim looked like a dark streak because only the band
 * was ever visible.
 */
export function groundEdgeTile(kind: Ground, edge: Edge, variant: number): Pix {
  const tile = groundTile(kind, variant);
  const { dark } = GROUND_RAMP[kind];
  const band = 2;
  const isol = new IsoPix(TILE_PX.w, TILE_PX.h, TILE_PX.ox, TILE_PX.oy);

  // The band: one step below the tile's own surface, dithered so it interlocks
  // with the plate rather than sitting on it as a border.
  //
  // The band uses the *opposite* checkerboard parity to `groundTile`'s own dark
  // facet. That is not arbitrary: `groundTile` already dithers some kinds with
  // this ramp's darkest step on the even lattice, so a band on the same parity
  // would overwrite those pixels with the colour already there and the rim
  // would vanish on `road` and `yard` while showing on the rest.
  const spans: Record<Edge, (wx: number, wy: number) => boolean> = {
    north: (_wx, wy) => wy <= band,
    west: (wx, _wy) => wx <= band,
    south: (_wx, wy) => wy >= TILE - band,
    east: (wx, _wy) => wx >= TILE - band,
  };
  const inBand = spans[edge];
  for (let wy = 0; wy <= TILE; wy++) {
    for (let wx = 0; wx <= TILE; wx++) {
      if (!inBand(wx, wy)) continue;
      if ((wx + wy) % 2 === 1) isol.plot(wx, wy, 0, dark);
    }
  }

  // The lip: the outermost row of the edge, solid in the ramp's darkest step.
  // This is the line that defines the plate, and it is the reason the band can
  // stay dithered.
  const lip: Record<Edge, [number, number][]> = {
    north: Array.from({ length: TILE + 1 }, (_, wx) => [wx, 0] as [number, number]),
    west: Array.from({ length: TILE + 1 }, (_, wy) => [0, wy] as [number, number]),
    south: Array.from({ length: TILE + 1 }, (_, wx) => [wx, TILE] as [number, number]),
    east: Array.from({ length: TILE + 1 }, (_, wy) => [TILE, wy] as [number, number]),
  };
  for (const [wx, wy] of lip[edge]) isol.plot(wx, wy, 0, GROUND_RAMP[kind].ramp[0]);

  // Composited over the tile rather than drawn into it, so the base tile stays
  // a pure single-kind surface the rest of the system can reason about.

  return tile.clone().blit(isol.pix, 0, 0);
}
